name: markdown-presubmit
on:
  push:
    branches: ['master']
  pull_request:
    paths: ['**.md']

jobs:
  lint:
    runs-on: ubuntu-latest
    container: ghcr.io/igorshubovych/markdownlint-cli:latest
    steps:
    - uses: actions/checkout@v2
    - name: markdownlint
      run: |
        markdownlint . \
          -i .git \
          -i docs/glome-login.md \
          --disable MD040 MD013
